### ISSUE TITLE
Not compatible with current version

### ISSUE THREAD

**Issue by psarossy** [cmuench/ulauncher-todoist#1]
Trying to add it on Manjaro/Arch, and it complatins that it's not compatible
![Screenshot_20190831_131723](https://user-images.githubusercontent.com/207358/64067150-cf7ad000-cbf1-11e9-9bee-06fe685c3c38.png)

**Comment by cmuench** [comment]
@psarossy I used Arch to develop the extension.
Which version of Ulauncher are you using?

It's only running in Ulauncher 5.

**Comment by psarossy** [comment]
I installed the default version on Manjaro, which is v5.3.0~beta1 currently (though the repo says 5.2.0-1)

**Comment by cmuench** [comment]
@psarossy thanks. I will check that this week. It's my first Ulauncher plugin. Let's see if it is a small issue.
Did you install the python dependency?

`pip3 install todoist-python`

**Comment by psarossy** [comment]
Yes, it's installed, but can't even get that far as in installer doesn't let me fetch the extension

**Comment by cmuench** [comment]
@psarossy I was able reproduce the problem. A file "versions.json" was missing which is not required if a local dev version is used.

Please try again. But do not expect to much... That's my first published extension.

**Comment by cmuench** [comment]
@psarossy I close the issue. If anything is broken on your machine, please re-open.
