### ISSUE TITLE
Feature Request > Add todo to a specific project

### ISSUE THREAD

**Issue by pascalbe-dev** [cmuench/ulauncher-todoist#7]
Hey, 
it would be great, if we would be able to add a todo to a specific project like how it is done in the todoist apps: 

`todo create Do something #MyProject` 

In this case, the new Task should be added to the MyProject project. It would be even nicer, if we got intellisense, when typing the "#". 

What do you think? I'd be glad to try to implement this myself and create a pull request, if you are up for the feature.

**Comment by cmuench** [comment]
@pascalbe-dev sounds like a great feature. Feel free to send a PR.

**Comment by pascalbe-dev** [comment]
Nice, I'll have a look at it within the next days 👍🏼
