### ISSUE TITLE
Crashed while adding to Ulauncher

### ISSUE THREAD

**Issue by bgrgv** [cmuench/ulauncher-todoist#9]
Message: 'com.github.cmuench.ulauncher-todoist'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 417, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.cmuench.ulauncher-todoist'

```

**Comment by cmuench** [comment]
@bgrgv Thanks for creating the issue.
Sadly the last time that I wrote some python code is more than a year ago.
Maybe the ulauncher dependencies changed. On my machine several other ulauncher plugins are currently crashing.
Can not promise that I can fix that issue soon.

**Comment by bgrgv** [comment]
Alright, got it :)

**Comment by cmuench** [comment]
Seems the same like here: 

https://github.com/Ulauncher/Ulauncher/issues/726
https://github.com/Ulauncher/Ulauncher/issues/716

**Comment by cmuench** [comment]
@bgrgv Most the time it's the missing dependency to todoist-python.

`pip3 install todoist-python`

**Comment by inamuu** [comment]
@bgrgv 

I got the same issue after upgrade Ubuntu 21.04 from 20.10.
Ulauncher was processess launched global python3.
But, It did not installed todoist-python at global.
So, I installed pip3 and todoist-python at global, I solved it.

I think it was not extension issue.
Because I hit this issue at other extensions too.

```
sudo apt install python3-pip
/usr/bin/pip3 install python3-todoist
```
